SUPABASE_URL=https://hucjsxbcqmeumghsktrb.supabase.co/rest/v1/
SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Y2pzeGJjcW1ldW1naHNrdHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyMDEwNDAsImV4cCI6MjEwNjc3NzA0MH0.X9i3SdzTZQ39mrGbakqajEjxDOBKTD39YEOJj3wwiA4
